### PR TITLE
TodoMVC example

### PR DESCRIPTION
**Pull request by cdelaorden**
I just rewrote the non-existing sample app to be a clone of TodoMVC. The code is pretty heavily commented, specially the stores/todos.js file. It also embraces some good practices, like:

1. Implementing "shouldComponentUpdate" in the todo item to speed up the full list rendering by 5x.

2. Changing "Dispatcher.messages" to an independent ./config/actions.js file, so the developer doesn't need to modify a *core* module (dispatcher) to add the app command logic. "Action" has a bigger semantic weight than "message". 

3. Remove all partial, only one-function require("xxx") calls that are known to create problems with testing frameworks.

4. For debugging and performance reasons, there's code that adds 1000 random todo items to the list, currently commented out in app.js. Uncomment to see and wait a little. :) Also, the Root component logs the full re-render update time, so you can spot heavy operations in the developer console.

## Changes from old "baseApp" ##
1. Remove the hasbang#! routing and use HTML5 in client router, to make it more modern.

## Known Issues ##
1. The last element in the list (at bottom) is sometimes difficult to interact with. Seems like a HTML/CSS issue.

## Pending / Nice to have in the future ##

1. Convert this into an npm package
2. Swap webmake for webpack, which is the standard with React
3. Try to remove common boilerplate code by providing some shortcuts/factory methods like "createStore", and so on.
4. Add a little server to illustrate using an external REST API.

### CODE REVIEW

**Comment by fuzzyalej** [comment]
I miss some more explanations on the readme file. Why use this approach? What are the interesting files?

Having comments in the code is fine but I think they are better placed in the readme file. What is a store? How can you use it? etc

**Comment by cdelaorden** [comment]
Hi

I didn't want to use the README as a blog post, which is probably what's needed for this. I'll start it, I already have even a nice image. ;)

redflow

**Comment by fuzzyalej** [comment]
awesome man :heart:

On Sunday, April 26, 2015, Carlos de la Orden <notifications@github.com>
wrote:

> Hi
>
> I didn't want to use the README as a blog post, which is probably what's
> needed for this. I'll start it, I already have even a nice image. ;)
>
> [image: redflow]
> <https://cloud.githubusercontent.com/assets/3973131/7336534/847ebd32-ec03-11e4-9719-4d48188c060d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redradix/redflow/pull/1#issuecomment-96347094>.
>


-- 
-
Alejandro Andrés
Partner at redradix.com

**Comment by WeRelax** [comment]
Thanks, Carlos! Good job. We needed another Todo in our lives :stuck_out_tongue_winking_eye:

**Comment by WeRelax** [comment]
@cdelaorden I have a question: what's the point of `src/config/actions.js`? I don't see the need to save all the string constants in a file. I mean: why is better to refer to some action as `TodoActions.TODO_UPDATE` instead of just `"TODO:UPDATE"`? I don't see any advanteges. In both cases, the code is coupled against a string (the property name in the first case, the action name in the second) so we are not gaining anything. Why don't use the action name directly?

**Comment by cdelaorden** [comment]
Hi @WeRelax 
I did it that way because it's more or less the standard way in Facebook Flux. In addition, having all that stuff in a single file, with comments if needed, allows a developer to simply open the actions file and find out what the application is about. It acts like a dictionary of what does this app do, which I really like. Oh, this is about adding todos, login users and broadcasting changes. Just by looking into a single file. 

There are a few glitches in RedFlow though: how do you manage Store to Store communication? I've using Dispatcher.emit from one to another but I think that breaks the circular flow in the graphic. I don't like coupling on to each other -that causes circular dependencies. Any suggestions? Example: in this todo list, depending on which activePage we're on (RootStore) show all/completed/active todos.

**Comment by WeRelax** [comment]
@cdelaorden I don't know, I'm still thinking it's a bit silly to have that kind of action listings. I know they do it like that in Flux, but that doesn't mean anything :) I don't buy the "its-an-overview-of-the-app" argument. It may hold true in this tiny little app, but as soon as your app grows that file will very probably become very long and messy. It's like putting all your functions in one file: If the app is really small is great because you can find everything quickly, but becomes unmanageable very very soon. But maybe is a matter of taste. I will wait until you use it in a big project and then we can discuss it again.

About the 'gitches': from my point of view, Store to Store communication is not a thing. They are just functions or objects calling each other. The only thing that makes them stores is that they listen to the Dispatcher. Is like asking: "how do you manage Event Handler to Event Handler communication?". There is no special protocol. If you want to re-emit events into the dispatcher, I don't see why you should not. (Ok, the graph will be violated. So what? This graphs are always liars, every single one of them. The depict the "usual" flow, but they are just learning aid, not a sacred rule. Sometimes it will make sense to re-emit an event. Don't let the graph stop you!!)

And the last thing: circular dependency. If you run into a circular dependency, your files are too big. Again, this is not a special case to stores. Is applicable to every other file of the app. Be careful, modularize and you'll be fine. And if worse comes to worst and you just hit that 1 in 1000 case when there is no way around the circular dependency, there are mechanisms to handle it.

Sorry I don't have a more "frameworky" answer. But I think one of the strengths of Flux/Redflow is their light weight. They are just a coupe of ideas working together, not a big fat manual of how to handle every aspect of the app (like Rails is). Stores, in particular, are just plain namespaces. Normal, ordinary vanilla code which happen to listen to some other guy. And I think that's how they should remain.

**Comment by cdelaorden** [comment]
I don't think I asked for anything like a "big fat manual", but it's fine I get your point. In my opinion some "frameworky" constraints sometimes make it easier for newcomers to learn the framework, and I was thinking in the other guys at RR who hasn't used it yet. That was good in Backbone for me, for example.

Regarding store to store, please have a look at gmv heaviest stores and see the awful spaghetti Miguel had to implement to avoid circular dependencies, like `require`ing another store inside a function body just to perform 1 operation. I personally think we could do better, but maybe it's just a matter of coding taste/style. It's pretty hard to mock/test stores, but then you'll probably answer that testing is not the big deal. :D

I'll let you write the blog post and do the graphic then, I'm clearly missing this project's direction.

**Comment by WeRelax** [comment]
Yes, you are right. Guidelines and constrains are good for newcomers. I keep forgetting that. We should have them, but always with an asterisk at the bottom of the page saying: "don't take this too seriously". I think we should look the problematic code together and discuss the issue with more context. I'm sure we can figure something out.

Please, reconsider about the post and the graph. There is no direction of the project other than us, discussing this kinds of things. We are both learning this as we go and there are still many things in the air neither of us knows how to do satisfactorily. Also, I didn't mean to offend your graph when I said it was a liar. It's a good graph, very clear and very pretty. Way, way better than anything I could do. Please, tell it I'm sorry :)

**Comment by cdelaorden** [comment]
Lol this PR thread is gong nuts :D I'll tell it but I can't promise anything!

**Pull request merged**
